### ISSUE TITLE
Issue with skummet

### ISSUE THREAD

**Issue by fnd009** [alexander-yakushev/foreclojure-android#5]
Hi,

I did a fresh foreclojure-android git clone and put a `:lean` into `:profiles` map of `project.clj` as following:

```
:lean
 [:release
  {:dependencies ^:replace [[org.skummet/clojure "1.7.0-r1"]
                            [neko/neko "4.0.0-alpha5"]]
   :exclusions [[org.clojure/clojure]
                [org.clojure-android/clojure]]
   :jvm-opts ["-Dclojure.compile.ignore-lean-classes=true"]
   :global-vars ^:replace {clojure.core/*warn-on-reflection* true}
   :android {:lean-compile true
             :proguard-execute true
             :proguard-conf-path "build/proguard-minify.cfg"}}]
```

When i run with `:lean` profile, I got this error:

```
$ lein with-profile lean do clean, droid doall
WARNING: Couldn't read the encryption key from file. Using empty encryption key.
(Warning: profile :android-common not found.)
(Warning: profile :android-release not found.)
Generating manifest...
Generating R.java files...
/tmp/foreclojure-android/res/values/styles.xml:3: error: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.

/tmp/foreclojure-android/res/values/styles.xml:6: error: Error: No resource found that matches the given name: attr 'colorAccent'.

/tmp/foreclojure-android/res/values/styles.xml:4: error: Error: No resource found that matches the given name: attr 'colorPrimary'.

/tmp/foreclojure-android/res/values/styles.xml:5: error: Error: No resource found that matches the given name: attr 'colorPrimaryDark'.


Abort execution.
Error encountered performing task 'do' with profile(s): 'lean'
Abort execution.
```

FYI, Everything going fine when I run with `:dev` profile. 

Am I missing something? Thanks in advance.

**Comment by fnd009** [comment]
Forgot to show debug

```
$ DEBUG=1 lein with-profile lean droid doall
Leiningen's classpath: /home/efendi/.lein/self-installs/leiningen-2.5.1-standalone.jar
WARNING: Couldn't read the encryption key from file. Using empty encryption key.
(Warning: profile :android-common not found.)
Applying task with-profile to [lean droid doall]
(Warning: profile :android-common not found.)
(Warning: profile :android-release not found.)
Applying task droid to (doall)
(Warning: profile :android-common not found.)
(Warning: profile :android-release not found.)
Extracting AAR dependencies:  #{[com.android.support/multidex 1.0.0 :extension aar]}
Generating manifest...
Merging secondary manifests: (#<File /tmp/foreclojure-android/target/release/aar-extracted/com.android.support_multidex_aar_1.0.0/AndroidManifest.xml>)
Generating R.java files...
/home/efendi/Android/Sdk/build-tools/22.0.1/aapt package -f -m -M /tmp/foreclojure-android/target/release/AndroidManifest.xml -S /tmp/foreclojure-android/target/release/res -S /tmp/foreclojure-android/res -S /tmp/foreclojure-android/target/release/aar-extracted/com.android.support_multidex_aar_1.0.0/res -I /home/efendi/Android/Sdk/platforms/android-21/android.jar -J /tmp/foreclojure-android/target/release/gen --output-text-symbols /tmp/foreclojure-android/target/release/gen --auto-add-overlay --generate-dependencies
/tmp/foreclojure-android/res/values/styles.xml:3: error: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.

/tmp/foreclojure-android/res/values/styles.xml:6: error: Error: No resource found that matches the given name: attr 'colorAccent'.

/tmp/foreclojure-android/res/values/styles.xml:4: error: Error: No resource found that matches the given name: attr 'colorPrimary'.

/tmp/foreclojure-android/res/values/styles.xml:5: error: Error: No resource found that matches the given name: attr 'colorPrimaryDark'.


Abort execution.
Error encountered performing task 'droid' with profile(s): 'lean'
clojure.lang.ExceptionInfo: Abort execution. {:exit-code 1, :suppress-msg false}
    at clojure.core$ex_info.invoke(core.clj:4403)
    at leiningen.core.main$exit.doInvoke(main.clj:162)
    at clojure.lang.RestFn.applyTo(RestFn.java:139)
    at clojure.core$apply.invoke(core.clj:626)
    at leiningen.core.main$abort.doInvoke(main.clj:172)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at leiningen.droid.utils$sh.doInvoke(utils.clj:324)
    at clojure.lang.RestFn.invoke(RestFn.java:3894)
    at leiningen.droid.code_gen$generate_resource_code.invoke(code_gen.clj:101)
    at leiningen.droid.code_gen$code_gen.invoke(code_gen.clj:120)
    at leiningen.droid.build$build.invoke(build.clj:177)
    at leiningen.droid$execute_subtask.invoke(droid.clj:98)
    at leiningen.droid$doall.doInvoke(droid.clj:48)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at clojure.core$apply.invoke(core.clj:626)
    at leiningen.droid$execute_subtask.invoke(droid.clj:101)
    at leiningen.droid$droid.doInvoke(droid.clj:65)
    at clojure.lang.RestFn.invoke(RestFn.java:423)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.core$apply.invoke(core.clj:626)
    at leiningen.core.main$partial_task$fn__6094.doInvoke(main.clj:263)
    at clojure.lang.RestFn.applyTo(RestFn.java:139)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:626)
    at leiningen.core.main$apply_task.invoke(main.clj:313)
    at leiningen.with_profile$with_profiles_STAR_.invoke(with_profile.clj:14)
    at leiningen.with_profile$apply_task_with_profiles.invoke(with_profile.clj:53)
    at leiningen.with_profile$with_profile$fn__11794.invoke(with_profile.clj:87)
    at clojure.core$mapv$fn__6311.invoke(core.clj:6353)
    at clojure.core.protocols$fn__6086.invoke(protocols.clj:143)
    at clojure.core.protocols$fn__6057$G__6052__6066.invoke(protocols.clj:19)
    at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
    at clojure.core.protocols$fn__6078.invoke(protocols.clj:54)
    at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13)
    at clojure.core$reduce.invoke(core.clj:6289)
    at clojure.core$mapv.invoke(core.clj:6353)
    at leiningen.with_profile$with_profile.doInvoke(with_profile.clj:84)
    at clojure.lang.RestFn.invoke(RestFn.java:467)
    at clojure.lang.Var.invoke(Var.java:394)
    at clojure.lang.AFn.applyToHelper(AFn.java:165)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.core$apply.invoke(core.clj:626)
    at leiningen.core.main$partial_task$fn__6094.doInvoke(main.clj:263)
    at clojure.lang.RestFn.applyTo(RestFn.java:139)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:626)
    at leiningen.core.main$apply_task.invoke(main.clj:313)
    at leiningen.core.main$resolve_and_apply.invoke(main.clj:319)
    at leiningen.core.main$_main$fn__6160.invoke(main.clj:392)
    at leiningen.core.main$_main.doInvoke(main.clj:385)
    at clojure.lang.RestFn.invoke(RestFn.java:457)
    at clojure.lang.Var.invoke(Var.java:394)
    at clojure.lang.AFn.applyToHelper(AFn.java:165)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.core$apply.invoke(core.clj:624)
    at clojure.main$main_opt.invoke(main.clj:315)
    at clojure.main$main.doInvoke(main.clj:420)
    at clojure.lang.RestFn.invoke(RestFn.java:512)
    at clojure.lang.Var.invoke(Var.java:409)
    at clojure.lang.AFn.applyToHelper(AFn.java:178)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
```

Thanks.

**Comment by fnd009** [comment]
After a week struggling with this error, finally I found the solution. I need to copy the AppCompat, data.json, etc dependencies into the `:lean` profile as well.

```
:lean
             [:release
              {:dependencies ^:replace [[org.skummet/clojure "1.7.0-r1"]
                                        [neko/neko "4.0.0-alpha5"]
                                        [com.android.support/appcompat-v7 "22.2.1" :extension "aar"]
                                        [org.clojure-android/data.json "0.2.6-SNAPSHOT"]]
               :exclusions [[org.clojure/clojure]
                            [org.clojure-android/clojure]]
               :jvm-opts ["-Dclojure.compile.ignore-lean-classes=true"]
               :global-vars ^:replace {clojure.core/*warn-on-reflection* true}
               :android {:use-debug-keystore true
                         :proguard-execute true
                         :proguard-conf-path "build/proguard-minify.cfg"
                         :lean-compile true
                         :skummet-skip-vars [;; You can list here var names that
                                             ;; you want to keep non-lean. E.g.:
                                             ;; "#'foo.bar/my-function"
                                             ]}}
```

Thanks.

**Comment by alexander-yakushev** [comment]
Oops,

I'm so sorry for not replying earlier. The bigger problem is that 4Clojure
app requires full Clojure compiler at runtime, so we can't really use
Skummet to minify it. It would be possible to achieve that with Pumpet,
which is an experimental Skummet with supported dynamic compilation, but
I've suspended that effort for now.

So in the end you'll be able to compile 4clojure with Skummet, but solving
tasks won't work. I'll be happy to help you if note questions arise. Sorry
again for leaving you hanging.

**Comment by fnd009** [comment]
Hi Alexander,

It's okay, I am in process learning Clojure by making simple Android app. That error arise on my app so I tried with 4clojure. Anyway it solved already and would ask again If i got any issue in future.

Btw, thanks for your hard work, I'm happy developing an Android app using Clojure because it is so fun and make me productive.

Thank you.

**Comment by alexander-yakushev** [comment]
You're welcome! I'm glad to hear that you enjoy using CoA.
